estate/urls.py
from django.conf.urls.static import static
from django.urls import include, re_path
from django.contrib import admin
from django.urls import path

from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
]

admin.site.site_header = "Администрация сайта усадьбы Уюта"
admin.site.index_title = "Лучший отдых"
if not settings.DEBUG:
    from django.views.static import serve

    urlpatterns += [re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT})]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path, register_converter

from main.converters import RoomTypeConverter, ServiceTypeConverter

from .views import HomeView, ServicesView, ServicesDetailView, PricesView, InfoView, ContactsView, RoomsView, \
    RoomsDetailView

register_converter(RoomTypeConverter, 'room_type')
register_converter(ServiceTypeConverter, 'service_type')
app_name = 'main'
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('services/<service_type:service_type>/', ServicesView.as_view(), name='services'),
    path('services/<int:number>/', ServicesDetailView.as_view(), name='services_detail'),
    path('prices/', PricesView.as_view(), name='prices'),
    path('info/', InfoView.as_view(), name='info'),
    path('contacts/', ContactsView.as_view(), name='contacts'),
    path('rooms/<room_type:room_type>/', RoomsView.as_view(), name='rooms'),
    path('rooms/<room_type:room_type>/<int:number>/', RoomsDetailView.as_view(), name='rooms_detail'),
]

main/models.py
import os.path

from django.db import models
from django.urls import reverse


def room_img_path(instance, filename):
    return os.path.join('room_images', str(instance.room.id), filename)


def service_img_path(instance, filename):
    return os.path.join('service_images', str(instance.service.id), filename)


def room_convenience_img_path(instance, filename):
    return os.path.join('room_convenience_icons', filename)


class ServicesManager(models.Manager):
    def special(self):
        return self.filter(isSpecial=True)

    def not_special(self):
        return self.filter(isSpecial=False)


class RoomCategory(models.Model):
    name = models.CharField(max_length=100, verbose_name="Название")

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"

    def __str__(self):
        return self.name


class Room(models.Model):
    id = models.IntegerField(primary_key=True, verbose_name="Номер комнаты")
    name = models.CharField(max_length=100, verbose_name="Заголовок")
    description = models.TextField(verbose_name="Описание")
    price = models.IntegerField(verbose_name="Цена")
    category = models.ForeignKey(RoomCategory, on_delete=models.DO_NOTHING, related_name="rooms",
                                 verbose_name="Категория")
    preview = models.ImageField("Превью", upload_to="room_previews/")

    objects = models.Manager()

    class Meta:
        verbose_name = "Номер"
        verbose_name_plural = "Номера"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('main:rooms_detail', kwargs={
            'room_type': self.category.name,
            'number': self.id,
        })


class Service(models.Model):
    id = models.IntegerField(primary_key=True, verbose_name="id услуги")
    name = models.CharField(max_length=100, verbose_name="Название услуги")
    description = models.TextField(verbose_name="Описание")
    price = models.IntegerField(verbose_name="Цена")
    isSpecial = models.BooleanField(verbose_name="Специальная услуга?", default=False)
    preview = models.ImageField("Превью", upload_to="services_previews/", blank=False)
    objects = models.Manager()
    manager = ServicesManager()

    class Meta:
        verbose_name = "Услуга"
        verbose_name_plural = "Услуги"

    def __str__(self):
        return self.name


class ServiceImage(models.Model):
    service = models.ForeignKey(Service, on_delete=models.CASCADE, related_name="images")
    image = models.ImageField("Изображение", upload_to=service_img_path)

    class Meta:
        verbose_name = "Фото-хранилище услуги"
        verbose_name_plural = "Фото-хранилище услуги"


class RoomImage(models.Model):
    room = models.ForeignKey(Room, on_delete=models.CASCADE, related_name="images")
    image = models.ImageField("Изображение", upload_to=room_img_path)

    class Meta:
        verbose_name = "Фото-хранилище номера"
        verbose_name_plural = "Фото-хранилище номера"


class RoomConvenience(models.Model):
    name = models.CharField(max_length=30, verbose_name="Название удобства")
    image = models.ImageField("Иконка удобства", upload_to=room_convenience_img_path)
    rooms = models.ManyToManyField(Room, related_name="convenience")
    price = models.PositiveIntegerField(blank=True, default=0)

    class Meta:
        verbose_name = "Удобства"
        verbose_name_plural = verbose_name

main/views.py
from django.views.generic import ListView, DetailView, TemplateView

from .models import Room, Service


class HomeView(TemplateView):
    template_name = 'main/home.html'
    extra_context = {
        'rooms': Room.objects.prefetch_related('images').all(),
        'services': Service.manager.not_special().prefetch_related('images').all(),
    }


class ServicesView(TemplateView):
    template_name = 'main/services.html'

    def get_context_data(self, **kwargs):
        super().get_context_data(**kwargs)
        queryset = Service.objects.all()

        services = {
            'indoor': [],
            'special': [],
        }

        for serv in queryset:
            if serv.isSpecial:
                services['special'] += [serv]
            else:
                services['indoor'] += [serv]

        kwargs.update(services)
        return kwargs


class ServicesDetailView(DetailView):
    template_name = 'main/services-detail.html'
    model = Service
    context_object_name = 'service'
    pk_url_kwarg = 'number'

    def get_queryset(self):
        queryset = super().get_queryset().prefetch_related('images')
        return queryset


class PricesView(ListView):
    template_name = 'main/prices.html'
    allow_empty = True


class InfoView(TemplateView):
    template_name = 'main/info.html'


class ContactsView(TemplateView):
    template_name = 'main/contacts.html'


class RoomsView(TemplateView):
    template_name = 'main/rooms.html'

    def get_context_data(self, **kwargs):
        super().get_context_data(**kwargs)
        rooms = {
            'standard': [],
            'half_luxe': [],
            'luxe': [],
        }
        for room in Room.objects.all():
            if room.category.name == 'standard':
                rooms['standard'] += [room]
            elif room.category.name == 'half-luxe':
                rooms['half_luxe'] += [room]
            else:
                rooms['luxe'] += [room]
        kwargs.update(rooms)
        return kwargs


class RoomsDetailView(DetailView):
    template_name = 'main/rooms-detail.html'
    model = Room
    context_object_name = 'room'
    pk_url_kwarg = 'number'

    def get_queryset(self):
        queryset = super().get_queryset().prefetch_related('images', 'convenience')
        return queryset

    def get_object(self, queryset=None):
        return super().get_object(queryset)

main/templates/main/components/reviews.html
{% load static %}
<div class="swiper reviewSwiper">
    <div class="swiper-wrapper">

        <div class="swiper-slide">
            <div class="reviews-container">
                <div class="review not-center-review">
                    <div class="review-author">
                        <h3>Юлия Зайцева</h3>
                        <img src="{% static 'main/img/5stars.png' %}" alt="">
                    </div>
                    <div class="review-text">
                        Останавливались на 1 ночь с двумя детьми в двухкомнатном номере в конце апреля 24г. Отель
                        очень понравился, все чисто и уютно. Есть общая кухня со всем необходимым. Номер так же был
                        чистый, с хорошей мебелью, большой ванной комнатой. Вокруг отеля тихо, в пешей доступности
                        кафе и магазины.
                    </div>
                    <a target="_blank"
                        href="https://yandex.ru/maps/org/148281453059/reviews?reviews%5BpublicId%5D=yb60n22q3v2hvp6afux8gdrfg4&si=4zhjw283wrmdfww7zdwqzuywwm&utm_source=review">
                        <div class="original-review">Посмотреть оригинал на <img
                                src="{% static 'main/img/yandex.png' %}" alt=""></div>
                    </a>
                </div>

                <div class="review">
                    <div class="review-author">
                        <h3>Olga Khramtsova</h3>
                        <img src="{% static 'main/img/5stars.png' %}" alt="">
                    </div>
                    <div class="review-text">
                        Останавливась проездом из Тбилиси в Москву. Очень чисто, уютно! Приятно находиться в номере.
                        Спасибо владельцамии администратору. Также благодарю за то, что гостевой дом дог-френдли:)
                    </div>
                    <a target="_blank"
                        href="https://yandex.ru/maps/org/148281453059/reviews?reviews%5BpublicId%5D=aucypez0aturybmetz02gqgp0r&si=4zhjw283wrmdfww7zdwqzuywwm&utm_source=review">
                        <div class="original-review">Посмотреть оригинал на <img
                                src="{% static 'main/img/yandex.png' %}" alt=""></div>
                    </a>
                </div>

            </div>
        </div>

        <div class="swiper-slide">
            <div class="reviews-container">
                <div class="review not-center-review">
                    <div class="review-author">
                        <h3>Наталья К.</h3>
                        <img src="{% static 'main/img/5stars.png' %}" alt="">
                    </div>
                    <div class="review-text">
                        Отдыхала в марте 2025 года в этом уютном госревом доме. Номер очень чистый и просторный.
                        Администратор приветливый все
                        рассказал и обьяснил. Постельное белье новое, матрац очень удобный. Рядом есть магазины и
                        очень удобно добираться в
                        Пятигорск и Железноводск. Всем очень довольна. Рекомендую на все 100 процентов.
                    </div>
                    <a target="_blank"
                        href="https://yandex.ru/maps/org/148281453059/reviews?reviews%5BpublicId%5D=grtxhu4r53vc5qeqfe4yq754rr&si=4zhjw283wrmdfww7zdwqzuywwm&utm_source=review">
                        <div class="original-review">Посмотреть оригинал на <img
                                src="{% static 'main/img/yandex.png' %}" alt=""></div>
                    </a>
                </div>

                <div class="review">
                    <div class="review-author">
                        <h3>Юлия Заберючинская</h3>
                        <img src="{% static 'main/img/5stars.png' %}" alt="">
                    </div>
                    <div class="review-text">
                        Минусы отсутствуют полностью!!! Отличное место, тихо, спокойно, уютно, чисто. Персонал
                        просто супер. Огромное спасибо, что Вы есть! Попавши сюда хоть раз, никогда не захочется в
                        другой дом. Уезжаю всегда с сожалением...
                    </div>
                    <a target="_blank"
                        href="https://yandex.ru/maps/org/148281453059/reviews?reviews%5BpublicId%5D=dfxj9zyg5pxv7110y8zj7m68pr&si=4zhjw283wrmdfww7zdwqzuywwm&utm_source=review">
                        <div class="original-review">Посмотреть оригинал на <img
                                src="{% static 'main/img/yandex.png' %}" alt=""></div>
                    </a>
                </div>

            </div>
        </div>

        <div class="swiper-slide">
            <div class="reviews-container">

                <div class="review">
                    <div class="review-author">
                        <h3>irinamosienko1978</h3>
                        <img src="{% static 'main/img/5stars.png' %}" alt="">
                    </div>
                    <div class="review-text">
                        Заехали в гостевой дом Усадьба уюта по рекомендации своих друзей, отдыхаем здесь с мужем уже
                        не в первый раз. Нам все нравится. Атмосфера комфорта и уюта. Отдыхали в разных номерах все
                        номера, очень чистые и комфортные. Всем рекомендую!!! Мы стали постоянными гостями. Большое
                        спасибо хозяевам и администраторам!!! Да, отдельно хотим отметить сауну и кафе в гостевом
                        доме, очень атмосферно!!! Поэтому приезжайте, будите доволльны и ценами и отношением к
                        гостям!!
                    </div>
                    <a target="_blank"
                        href="https://yandex.ru/maps/org/148281453059/reviews?reviews%5BpublicId%5D=4r4vhmnqf600uzav6dbvtrxgzr&si=4zhjw283wrmdfww7zdwqzuywwm&utm_source=review">
                        <div class="original-review">Посмотреть оригинал на <img
                                src="{% static 'main/img/yandex.png' %}" alt=""></div>
                    </a>
                </div>

                <div class="review not-center-review">
                    <div class="review-author">
                        <h3>Tatyana Koryakina</h3>
                        <img src="{% static 'main/img/5stars.png' %}" alt="">
                    </div>
                    <div class="review-text">
                        Гостевой дом расположен среди частного сектора, хорошая асфальтовая дорога для подъезда. В
                        шаговой доступности магазины, кафе, пункт Wallsberry, храм. Радушные хозяева, везде чисто,
                        свежий ремонт, чистое бельё. Как во многих гостевых домах нужно разуться при входе, берите
                        сменную обуви или вам предложат тапочки. На обоих этажах кухни, со всеми необходимым -
                        посуда, кастрюли, холодильник. Номер уютный, тёплый, тихое место. Есть полотенца, гель для
                        душа. Работает телевизор, кондиционер, есть WiFi на хорошей скорости, сотовая связь
                        устойчива. Мы были в марте 2024 г проездом на Эльбрус. Рекомендую!
                    </div>
                    <a target="_blank"
                        href="https://yandex.ru/maps/org/148281453059/reviews?reviews%5BpublicId%5D=4tu3vkaex694u51fgz5hwuy85r&si=4zhjw283wrmdfww7zdwqzuywwm&utm_source=review">
                        <div class="original-review">Посмотреть оригинал на <img
                                src="{% static 'main/img/yandex.png' %}" alt=""></div>
                    </a>
                </div>

            </div>
        </div>
        <div class="swiper-slide">
            <div class="reviews-container">

                <div class="review not-center-review">
                    <div class="review-author">
                        <h3>Александр Б.</h3>
                        <img src="{% static 'main/img/5stars.png' %}" alt="">
                    </div>
                    <div class="review-text">
                        Этот дом на 1000% оправдывает свое название. Мы переночевали только одну ночь, но у нас
                        только самые положительные оценки и эмоции об этом месте. Нас встретили приветливые и
                        добродушные хозяева, сделали хорошую скидку. По уюту и отношению к гостям видно, что вы
                        любите свой дом и гостей. К вам хочется ещё раз вернуться. Успеха вам и процветания. Уже 2
                        разв в данном месте останавливались, всё СУПЕР
                    </div>
                    <a target="_blank"
                        href="https://yandex.ru/maps/org/148281453059/reviews?reviews%5BpublicId%5D=zx7etgpjtukuxrj7nqe4au6zyc&si=4zhjw283wrmdfww7zdwqzuywwm&utm_source=review">
                        <div class="original-review">Посмотреть оригинал на <img
                                src="{% static 'main/img/yandex.png' %}" alt=""></div>
                </div></a>

                <div class="review">
                    <div class="review-author">
                        <h3>Елена Анютина</h3>
                        <img src="{% static 'main/img/5stars.png' %}" alt="">
                    </div>
                    <div class="review-text">
                        Очень уютная гостиница. Есть кухня, где можно что-нибудь приготовить. В номере есть чайник,
                        кружки, чай и т.д. Номер большой и чистый. Рекомендуем для посещения ( особенно кто
                        путешествует на машине). Хорошее месторасположение между Железноводском и Пятигорском
                    </div>
                    <a target="_blank"
                        href="https://yandex.ru/maps/org/148281453059/reviews?reviews%5BpublicId%5D=whpcn3wt2kf9bhuanjkvt0atv8&si=4zhjw283wrmdfww7zdwqzuywwm&utm_source=review">
                        <div class="original-review">Посмотреть оригинал на <img
                                src="{% static 'main/img/yandex.png' %}" alt=""></div>
                    </a>
                </div>

            </div>
        </div>
        <div class="swiper-slide">
            <div class="reviews-container">

                <div class="review">
                    <div class="review-author">
                        <h3>Алексей Мосиенко</h3>
                        <img src="{% static 'main/img/5stars.png' %}" alt="">
                    </div>
                    <div class="review-text">
                        Отличное место, очень уютно и чисто. Шикарное место, как для отдыха, так и для проведения
                        различных торжеств. В Усадьбе есть комфортабельные номера, прекрасная баня, шашлычная зона и
                        банкетные зал в стиле охотничьего домика. Великолепная отделка интерьера. Хозяева,
                        прекрасные люди . Всем советую посетить. Цены приемлимые. Постоянным клиентам делают скидки.
                    </div>
                    <a target="_blank"
                        href="https://yandex.ru/maps/org/148281453059/reviews?reviews%5BpublicId%5D=wr3qe908x7138npdnjeuajghbg&si=4zhjw283wrmdfww7zdwqzuywwm&utm_source=review">
                        <div class="original-review">Посмотреть оригинал на <img
                                src="{% static 'main/img/yandex.png' %}" alt=""></div>
                    </a>
                </div>

                <div class="review not-center-review">
                    <div class="review-author">
                        <h3>Анна И.</h3>
                        <img src="{% static 'main/img/5stars.png' %}" alt="">
                    </div>
                    <div class="review-text">
                        Отличное место. Чисто, уютно, мебель и текстиль новые. Я слегка брезгливая, но в этом доме
                        нестрашно даже босиком в комнате походить)
                        Не вдавались в подробности изначально, от соседей по комнате узнали, что сзади есть летняя
                        кухня с мангальной зоной, от которой наши соседи тоже были в восторге)
                        Очень рекомендую, своих денег комнаты точно стоят.
                        Внутри: отдельный су, телевизор со всеми нужными каналами, кондиционер, мини-холодильник в
                        шкафчике, полотенца с запасом, индивидуальные отельные наборы гигиены. Варианты освещения
                        комнаты на любой вкус. Бесплатный вайфай ( подключаться не пробовали, т.к. отлично ловил
                        мобильный интернет)
                    </div>
                    <a target="_blank"
                        href="https://yandex.ru/maps/org/148281453059/reviews?reviews%5BpublicId%5D=uwrxfay5w411mhgty89eg06eqc&si=4zhjw283wrmdfww7zdwqzuywwm&utm_source=review">
                        <div class="original-review">Посмотреть оригинал на <img
                                src="{% static 'main/img/yandex.png' %}" alt=""></div>
                    </a>
                </div>

            </div>
        </div>
    </div>
    <div class="swiper-pagination"></div>
</div>

main/templates/main/components/room-container.html
<div class="room-wrapper">
    <a href="{% url 'main:rooms_detail' room.category room.id %}">
        <div class="room-image">
            <div class="room-on-img-price">№{{room.id}}</div>
            <img src="{{ room.preview.url }}" alt="{{ room.name }}">
            <div class="room-on-img">{{room.category}}</div>
        </div>
        <div class="room-descr">
            <p class="room-descr-price">{{room.price}}₽</p>
            <p>{{room.description|truncatewords:8|safe }}</p>
        </div>
    </a>
</div>

main/templates/main/components/rooms-list.html
<div class="margin-for-grid">
    <div class="list-container-grid">
        {% for room in rooms %}
        {% include './room-container.html' %}
        {% endfor %}
    </div>
</div>

main/templates/main/components/service-container.html
<div class="room-wrapper">
    <a href="{% url 'main:services_detail' service.id %}">
        <div class="room-image">
            <div class="room-on-img-price">{{service.name}}</div>
            <img src="{{ service.preview.url }}" alt="{{ service.name }}">
            {% if service.isSpecial %}
            <div class="room-on-img">Специальная</div>
            {% else %}
            <div class="room-on-img">Стандартная</div>
            {% endif %}
        </div>
        <div class="room-descr">
            <p class="room-descr-price">{{service.price}}₽</p>
            <p>{{ service.description|truncatewords:8|safe }}</p>
        </div>
    </a>
</div>

main/templates/main/components/services-list.html
<div class="margin-for-grid">
    <div class="list-container-grid">
        {% for service in services %}
        {% include './service-container.html' %}
        {% endfor %}
    </div>
</div>

main/templates/main/contacts.html
{% extends 'base.html' %}

main/templates/main/home.html
{% extends 'base.html' %}
{% load static %}
{% block style %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css" />
<link rel="stylesheet" href="{% static 'main/css/home.css' %}">
<link rel="stylesheet" href="{% static 'main/css/review.css' %}">
{% endblock %}
{% block content %}
<div class="swiper-inozemcevo">
    <div class="swiper-wrapper">
        <div class="swiper-slide">
            <img src="{% static 'main/img/mainslider/7.jpg' %}" alt="">
        </div>
        <div class="swiper-slide">
            <img src="{% static 'main/img/mainslider/8.jpg' %}" alt="">
        </div>
        <div class="swiper-slide">
            <img src="{% static 'main/img/mainslider/4.jpg' %}" alt="">
        </div>
        <div class="swiper-slide">
            <img src="{% static 'main/img/mainslider/5.jpg' %}" alt="">
        </div>
        <div class="swiper-slide">
            <img src="{% static 'main/img/mainslider/2.jpg' %}" alt="">
        </div>
        <div class="swiper-slide">
            <img src="{% static 'main/img/mainslider/3.jpg' %}" alt="">
        </div>
        <div class="swiper-slide">
            <img src="{% static 'main/img/mainslider/1.jpg' %}" alt="">
        </div>
        <div class="swiper-slide">
            <img src="{% static 'main/img/mainslider/6.jpg' %}" alt="">
        </div>
    </div>
    <div class="swiper-button-next"></div>
    <div class="swiper-button-prev"></div>
    <div class="swiper-pagination"></div>
</div>

<div class="content-wrapper">
    <h2>Номера</h2>
    <div class="animated-line"></div>
    {% include './components/rooms-list.html'%}
</div>

<div class="content-wrapper">
    <h2>Услуги</h2>
    <div class="animated-line"></div>
    {% include './components/services-list.html'%}
</div>

<div class="content-wrapper">
    <h2>Почему выбирают нас?</h2>
    <div class="animated-line"></div>
    {% include './components/reviews.html' %}
</div>


<div id="map"></div>
{% endblock %}

{% block js %}
<script src="{% static 'node_modules/swiper/swiper-bundle.min.js' %}"></script>
<script src="https://api-maps.yandex.ru/2.1/?apikey=ваш API-ключ&lang=ru_RU" type="text/javascript"></script>
<script src="{% static 'main/js/home.js' %}"></script>
{% endblock %}

main/templates/main/info.html
{% extends 'base.html' %}
{% load static %}
{% block style %}
<link rel="stylesheet" href="{% static 'main/css/home.css' %}">
<link rel="stylesheet" href="{% static 'main/css/info.css' %}">
{% endblock %}
{% block content %}
<div class="content-wrapper">
    <h2>Основная информация</h2>
    <div class="animated-line"></div>

    <div class="info-list">
        <p>
            Прекрасный вариант, чтобы отдохнуть между прогулками по городу. Гостевой дом «Гостевой дом Усадьба Уюта»
            расположен в Иноземцево. Этот гостевой дом находится 1 км от центра города. Рядом с гостевым домом —
            Место дуэли Лермонтова, Комсомольский парк и Провал.</p>
        <img src="{% static 'main/img/ss1.jpg' %}" alt="">
        <img src="{% static 'main/img/ss2.jpg' %}" alt="">
        <p>
            Бесплатный Wi-Fi на территории поможет всегда оставаться на связи. Для путешественников на машине
            организована парковка. Также для гостей в гостевом доме: сауна. Среди развлечений на территории —
            площадка для пикника и площадка для барбекю.</p>
    </div>
</div>

<div class="content-wrapper">
    <h2>Возможности гостевого дома</h2>
    <div class="animated-line"></div>
    <div class="info-possibilities">
        <div class="info-possibility-ex">
            <img src="" alt="">
        </div>
    </div>
</div>

<div class="content-wrapper">
    <h2>На что стоит обратить внимание</h2>
    <div class="animated-line"></div>

</div>
{% block js %}
<script src="{% static 'main/js/home.js' %}"></script>
{% endblock %}
{% endblock %}

main/templates/main/prices.html
{% extends 'base.html' %}

main/templates/main/rooms-detail.html
{% extends 'base.html' %}
{% load static %}
{% block style %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css" />
<link rel="stylesheet" href="{% static 'main/css/home.css' %}">
<link rel="stylesheet" href="{% static 'main/css/room-detail.css' %}">
{% endblock %}

{% block content %}
<div class="content-wrapper">
    <div class="roominfo-grid">
        <div class="swiper swiperRoomInfo">
            <div class="swiper-wrapper">
                {% for image in room.images.all %}
                <div class="swiper-slide">
                    <div class="swiper-zoom-container">
                        <a class="fslightbox-swiper" href="{{ image.image.url }}" data-fslightbox="room-gallery"
                            data-type="image">
                            <img src="{{ image.image.url }}" />
                        </a>
                    </div>
                </div>
                {% endfor %}
            </div>
            <div class="swiper-button-next"></div>
            <div class="swiper-button-prev"></div>
            <div class="swiper-pagination"></div>
            <div class="swipper-fullscreen"><img src="{% static 'main/img/full-screen.png' %}" alt=""></div>
        </div>

        <div class="roominfo-maininfo">
            <h3>{{ room.name }}</h3>
            <div class="dull-line"></div>
            <p>{{ room.description|safe }}</p>
            <div class="roominfo-price">
                <span>{{ room.price }} ₽/ день</span>
            </div>
            <div class="roominfo-convenience-grid">
                {% for convenience in room.convenience.all %}
                <div class="roominfo-convenience-el">
                    <div class="flex-row">
                        <img src="{{ convenience.image.url }}" alt="">
                        <div>{{ convenience.name }}</div>
                    </div>
                    {% if covenience.price %}
                    <span>{{covenience.price}}</span>
                    {% endif %}
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block js %}
<script src="{% static 'main/js/home.js' %}"></script>
<script src="{% static 'node_modules/swiper/swiper-bundle.min.js' %}"></script>
<script src="{% static 'main/js/room_detail.js' %}"></script>
<script src="{% static 'node_modules/fslightbox/index.js' %}"></script>
{% endblock %}

main/templates/main/rooms.html
{% extends 'base.html' %}
{% load static %}
{% block style %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css" />
<link rel="stylesheet" href="{% static 'main/css/home.css' %}">
{% endblock %}

{% block content %}
<div class="content-wrapper">
    <h2 id="rooms-standard">Стандарт</h2>
    <div class="animated-line"></div>
    {% include './components/rooms-list.html' with rooms=standard %}
</div>
<div class="content-wrapper">
    <h2 id="rooms-half-luxe">Полулюкс</h2>
    <div class="animated-line"></div>
    {% include './components/rooms-list.html' with rooms=half_luxe %}
</div>
<div class="content-wrapper">
    <h2 id="rooms-luxe">Люкс</h2>
    <div class="animated-line"></div>
    {% include './components/rooms-list.html' with rooms=luxe %}
</div>
{% endblock %}

{% block js %}
<script src="{% static 'main/js/home.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js"></script>
{% endblock %}